compressionLevel: mixed

nodeLinker: node-modules

npmScopes:
  awesome.me:
    npmAuthToken: "${GAR_TOKEN-}"
    npmRegistryServer: "https://europe-west9-npm.pkg.dev/intescia-group-tools/all-in-one"
  doubletrade:
    npmAuthToken: "${GAR_TOKEN-}"
    npmRegistryServer: "https://europe-west9-npm.pkg.dev/intescia-group-tools/all-in-one"
  fortawesome:
    npmAuthToken: "${GAR_TOKEN-}"
    npmRegistryServer: "https://europe-west9-npm.pkg.dev/intescia-group-tools/all-in-one"

plugins:
  - path: .yarn/plugins/@intescia/yarn-plugin-gcloud-token-1.0.1.cjs
    spec: "https://storage.googleapis.com/intescia-public-bucket/yarn-plugin-gcloud-token-1.0.1.cjs"